### ISSUE TITLE
Mapbox logo usage on launch screen

### ISSUE THREAD

**Issue by friedbunny** [friedbunny/treble#1]
Is this acceptable according to [Mapbox's branding terms](https://www.mapbox.com/about/press-kit/)? This demo app was started as part of a sprint week at their DC office, but it's hosted on my personal account and I don't actually work for them.

**Why use it?**
- It's awesome
- I'm not a designer :wink:

**Why shouldn't we use it?**
- Confusing — This app displays three companies' maps, not just Mapbox's
- Potentially against Mapbox terms

![img_3258](https://cloud.githubusercontent.com/assets/1198851/7441950/25e9eb52-f0b3-11e4-9331-c4ad80e8eae3.PNG)

/cc @incanus

**Comment by incanus** [comment]
Nah this is fine. You aren't trying to sell anything. And this ticket is disclaimer enough.
